/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author m10816361
 */
public class Tela_Principal extends javax.swing.JFrame {

    Tela_Buscar_Pedidos buscar_pedidos = new Tela_Buscar_Pedidos();
    Tela_Usuarios tela_usuarios = new Tela_Usuarios();
    Tela_cliente editar_cliente = new Tela_cliente();
    Tela_Produto editar_produto = new Tela_Produto();
    Tela_Despesa despesa = new Tela_Despesa();
    Tela_Patrimonio patrimonio;
    Tela_relatorio relatorio = new Tela_relatorio();
    Tela_sobre sobre = new Tela_sobre();
    Tela_Inserir_Pedidos inserir_pedidos;

    /**
     * Creates new form TelaPrincipal
     */
    public Tela_Principal() {
        initComponents();
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    public void setjMenuItem1(JMenuItem jMenuItem1) {
        this.jMenuItem1 = jMenuItem1;
    }

    public JPanel getjPanel1() {
        return panel_desktop;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.panel_desktop = jPanel1;
    }

    public JLabel getLbl_bem_vindo() {
        return lbl_bem_vindo;
    }

    public void setLbl_bem_vindo(JLabel lbl_bem_vindo) {
        this.lbl_bem_vindo = lbl_bem_vindo;
    }

    public JLabel getLbl_data_atual() {
        return lbl_data_atual;
    }

    public void setLbl_data_atual(JLabel lbl_data_atual) {
        this.lbl_data_atual = lbl_data_atual;
    }

    public JLabel getLbl_usuario() {
        return lbl_usuario;
    }

    public void setLbl_usuario(JLabel lbl_usuario) {
        this.lbl_usuario = lbl_usuario;
    }

    public JMenu getMenu_cliente() {
        return menu_cliente;
    }

    public void setMenu_cliente(JMenu menu_cliente) {
        this.menu_cliente = menu_cliente;
    }

    public JMenu getMenu_despesa() {
        return menu_despesa;
    }

    public void setMenu_despesa(JMenu menu_despesa) {
        this.menu_despesa = menu_despesa;
    }

    public JMenu getMenu_opcoes() {
        return menu_opcoes;
    }

    public void setMenu_opcoes(JMenu menu_opcoes) {
        this.menu_opcoes = menu_opcoes;
    }

    public JMenu getMenu_patrimonio() {
        return menu_patrimonio;
    }

    public void setMenu_patrimonio(JMenu menu_patrimonio) {
        this.menu_patrimonio = menu_patrimonio;
    }

    public JMenu getMenu_produto() {
        return menu_produto;
    }

    public void setMenu_produto(JMenu menu_produto) {
        this.menu_produto = menu_produto;
    }

    public JMenu getMenu_receita() {
        return menu_pedidos;
    }

    public void setMenu_receita(JMenu menu_receita) {
        this.menu_pedidos = menu_receita;
    }

    public JMenu getMenu_relatorio() {
        return menu_relatorio;
    }

    public void setMenu_relatorio(JMenu menu_relatorio) {
        this.menu_relatorio = menu_relatorio;
    }

    public JMenuItem getMenu_sobre() {
        return menu_sobre;
    }

    public void setMenu_sobre(JMenuItem menu_sobre) {
        this.menu_sobre = menu_sobre;
    }

    public JMenu getMenu_usuario() {
        return menu_usuario;
    }

    public void setMenu_usuario(JMenu menu_usuario) {
        this.menu_usuario = menu_usuario;
    }

    public JMenuItem getMenu_usuario_manutencao() {
        return menu_usuario_manutencao;
    }

    public void setMenu_usuario_manutencao(JMenuItem menu_usuario_manutencao) {
        this.menu_usuario_manutencao = menu_usuario_manutencao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_desktop = new javax.swing.JPanel();
        lbl_bem_vindo = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        lbl_data_atual = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_cliente = new javax.swing.JMenu();
        menu_editar_cliente = new javax.swing.JMenuItem();
        menu_produto = new javax.swing.JMenu();
        jmenu_produto = new javax.swing.JMenuItem();
        menu_patrimonio = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        menu_pedidos = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menu_despesa = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menu_usuario = new javax.swing.JMenu();
        menu_usuario_manutencao = new javax.swing.JMenuItem();
        menu_relatorio = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        menu_opcoes = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menu_sobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout panel_desktopLayout = new javax.swing.GroupLayout(panel_desktop);
        panel_desktop.setLayout(panel_desktopLayout);
        panel_desktopLayout.setHorizontalGroup(
            panel_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
        );
        panel_desktopLayout.setVerticalGroup(
            panel_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );

        lbl_bem_vindo.setText("Bem vindo: ");

        menu_cliente.setText("Cliente");

        menu_editar_cliente.setText("Cadastro");
        menu_editar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_editar_clienteActionPerformed(evt);
            }
        });
        menu_cliente.add(menu_editar_cliente);

        jMenuBar1.add(menu_cliente);

        menu_produto.setText("Produto");

        jmenu_produto.setText("Cadastro");
        jmenu_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_produtoActionPerformed(evt);
            }
        });
        menu_produto.add(jmenu_produto);

        jMenuBar1.add(menu_produto);

        menu_patrimonio.setText("Patrimônio");

        jMenuItem4.setText("Cadastro");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menu_patrimonio.add(jMenuItem4);

        jMenuBar1.add(menu_patrimonio);

        menu_pedidos.setText("Vendas");

        jMenuItem3.setText("Inserir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menu_pedidos.add(jMenuItem3);

        jMenuItem5.setText("Visualizar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menu_pedidos.add(jMenuItem5);

        jMenuBar1.add(menu_pedidos);

        menu_despesa.setText("Despesas");

        jMenuItem2.setText("Cadastro");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu_despesa.add(jMenuItem2);

        jMenuBar1.add(menu_despesa);

        menu_usuario.setText("Usuário");

        menu_usuario_manutencao.setText("Manutenção");
        menu_usuario_manutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_usuario_manutencaoActionPerformed(evt);
            }
        });
        menu_usuario.add(menu_usuario_manutencao);

        jMenuBar1.add(menu_usuario);

        menu_relatorio.setText("Relatório");

        jMenuItem6.setText("Exibir");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menu_relatorio.add(jMenuItem6);

        jMenuBar1.add(menu_relatorio);

        menu_opcoes.setText("Opções");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_opcoes.add(jMenuItem1);

        menu_sobre.setText("Sobre");
        menu_sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_sobreActionPerformed(evt);
            }
        });
        menu_opcoes.add(menu_sobre);

        jMenuBar1.add(menu_opcoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbl_bem_vindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_data_atual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_bem_vindo))
                    .addComponent(lbl_data_atual, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Date data_atual = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.FULL);
        lbl_data_atual.setText(formatador.format(data_atual));
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menu_usuario_manutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_usuario_manutencaoActionPerformed
        fecha_janelas();
        tela_usuarios.setVisible(true);
        tela_usuarios.setLocation(200, 15);
        panel_desktop.add(tela_usuarios);

        // TODO add your handling code here:
    }//GEN-LAST:event_menu_usuario_manutencaoActionPerformed

    private void menu_sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_sobreActionPerformed

        fecha_janelas();
        sobre.setVisible(true);
        panel_desktop.add(sobre);

        // TODO add your handling code here:
    }//GEN-LAST:event_menu_sobreActionPerformed

    private void menu_editar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_editar_clienteActionPerformed
        fecha_janelas();
        editar_cliente.setVisible(true);
        editar_cliente.setLocation(15, 15);
        panel_desktop.add(editar_cliente);

        // TODO add your handling code here:
    }//GEN-LAST:event_menu_editar_clienteActionPerformed

    private void jmenu_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_produtoActionPerformed
        fecha_janelas();
        editar_produto.setVisible(true);
        editar_produto.setLocation(50, 15);
        panel_desktop.add(editar_produto);

    }//GEN-LAST:event_jmenu_produtoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        fecha_janelas();
        despesa.setVisible(true);
        despesa.setLocation(25, 15);
        panel_desktop.add(despesa);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        fecha_janelas();
        inserir_pedidos = new Tela_Inserir_Pedidos();
        inserir_pedidos.setLocation(50, 15);
        inserir_pedidos.setVisible(true);
        panel_desktop.add(inserir_pedidos);   // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        fecha_janelas();
        try {
            patrimonio = new Tela_Patrimonio();
            patrimonio.setVisible(true);
            panel_desktop.add(patrimonio);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        fecha_janelas();
        buscar_pedidos.setVisible(true);
        buscar_pedidos.setLocation(75, 15);
        panel_desktop.add(buscar_pedidos);   // TODO add your handling code her        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        fecha_janelas();
        relatorio.setVisible(true);
        buscar_pedidos.setLocation(75, 15);
        panel_desktop.add(relatorio);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    public void fecha_janelas() {

        if (buscar_pedidos != null) {
            buscar_pedidos.dispose();
        }
        if (tela_usuarios != null) {
            tela_usuarios.dispose();
        }
        if (editar_cliente != null) {
            editar_cliente.dispose();
        }
        if (editar_produto != null) {
            editar_produto.dispose();
        }
        if (despesa != null) {
            despesa.dispose();
        }
        if (patrimonio != null) {
            patrimonio.dispose();
        }
        if (relatorio != null) {
            relatorio.dispose();
        }
        if (sobre != null) {
            sobre.dispose();
        }
        if (inserir_pedidos != null) {
            inserir_pedidos.dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jmenu_produto;
    private javax.swing.JLabel lbl_bem_vindo;
    private javax.swing.JLabel lbl_data_atual;
    public javax.swing.JLabel lbl_usuario;
    private javax.swing.JMenu menu_cliente;
    private javax.swing.JMenu menu_despesa;
    private javax.swing.JMenuItem menu_editar_cliente;
    private javax.swing.JMenu menu_opcoes;
    private javax.swing.JMenu menu_patrimonio;
    private javax.swing.JMenu menu_pedidos;
    private javax.swing.JMenu menu_produto;
    private javax.swing.JMenu menu_relatorio;
    private javax.swing.JMenuItem menu_sobre;
    private javax.swing.JMenu menu_usuario;
    private javax.swing.JMenuItem menu_usuario_manutencao;
    private javax.swing.JPanel panel_desktop;
    // End of variables declaration//GEN-END:variables

}
