/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import Classes.Usuario;
import DAO.UsuarioDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author m10816361
 */
public class Tela_Usuarios extends javax.swing.JInternalFrame {

    public JButton getBtn_atualizar() {
        return btn_atualizar;
    }

    public void setBtn_atualizar(JButton btn_atualizar) {
        this.btn_atualizar = btn_atualizar;
    }

    public JLabel getLbl_nova_senha() {
        return lbl_nova_senha;
    }

    public void setLbl_nova_senha(JLabel lbl_nova_senha) {
        this.lbl_nova_senha = lbl_nova_senha;
    }

    public JLabel getLbl_senha_atual() {
        return lbl_senha_atual;
    }

    public void setLbl_senha_atual(JLabel lbl_senha_atual) {
        this.lbl_senha_atual = lbl_senha_atual;
    }

    public JLabel getLbl_usuario() {
        return lbl_usuario;
    }

    public void setLbl_usuario(JLabel lbl_usuario) {
        this.lbl_usuario = lbl_usuario;
    }

    public JTextField getTxt_nova_senha() {
        return txt_nova_senha;
    }

    public JTextField getTxt_usuario() {
        return txt_usuario;
    }

    public void setTxt_usuario(JTextField txt_usuario) {
        this.txt_usuario = txt_usuario;
    }

    /**
     * Creates new form Tela_usuarios
     */
    public Tela_Usuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_usuario = new javax.swing.JLabel();
        lbl_senha_atual = new javax.swing.JLabel();
        lbl_nova_senha = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        btn_atualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbl_nova_senha1 = new javax.swing.JLabel();
        txt_senha_atual = new javax.swing.JPasswordField();
        txt_nova_senha = new javax.swing.JPasswordField();
        txt_repetir_nova_senha = new javax.swing.JPasswordField();

        setBorder(null);
        setClosable(true);
        setMaximizable(true);

        lbl_usuario.setText("Usuário:");

        lbl_senha_atual.setText("Senha atual:");

        lbl_nova_senha.setText("Nova Senha:");

        btn_atualizar.setText("Atualizar");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tela de Atualização de Senha:");

        lbl_nova_senha1.setText("Repita a Nova Senha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_usuario)
                            .addComponent(lbl_senha_atual)
                            .addComponent(lbl_nova_senha)
                            .addComponent(lbl_nova_senha1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_atualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_usuario)
                            .addComponent(txt_senha_atual)
                            .addComponent(txt_nova_senha)
                            .addComponent(txt_repetir_nova_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_usuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_senha_atual)
                    .addComponent(txt_senha_atual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nova_senha)
                    .addComponent(txt_nova_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nova_senha1)
                    .addComponent(txt_repetir_nova_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_atualizar)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed

        Usuario usuario = new Usuario();
        UsuarioDAO usuarioDao = new UsuarioDAO();
        boolean atualizar = false;
        boolean autenticar = false;

        try {
            if (txt_nova_senha.getText().trim().equals("") || txt_repetir_nova_senha.getText().trim().equals("")
                    || txt_repetir_nova_senha.getText().trim().equals("") || txt_usuario.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Erro, todos os campos devem ser digitados.");
            } else {
                String usr = new String(txt_usuario.getText());
                String senha = new String(txt_senha_atual.getText());
                String novaSenha = new String(txt_nova_senha.getText());
                String repeteSenha = new String(txt_repetir_nova_senha.getText());
                usuario.setNome(usr);
                usuario.setSenha(senha);

                if (novaSenha.equals(repeteSenha)) {
                    autenticar = usuarioDao.buscarUsuario(usuario);
                    if (autenticar == true) {
                        usuario.setSenha(novaSenha);
                        atualizar = usuarioDao.Atualizar(usuario);
                        limpar();
                        JOptionPane.showConfirmDialog(null, "Senha Atualizada com sucesso.");
                    } else {
                        JOptionPane.showConfirmDialog(null, " Usuário ou senha inválidos.");
                    }
                } else {
                    JOptionPane.showConfirmDialog(null, " Novas Senhas Não Conferem, favor digite os Dados Novamente.");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela_Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_atualizarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    private void limpar() {
        txt_usuario.setText(null);
        txt_senha_atual.setText(null);
        txt_nova_senha.setText(null);
        txt_repetir_nova_senha.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atualizar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_nova_senha;
    private javax.swing.JLabel lbl_nova_senha1;
    private javax.swing.JLabel lbl_senha_atual;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JPasswordField txt_nova_senha;
    private javax.swing.JPasswordField txt_repetir_nova_senha;
    private javax.swing.JPasswordField txt_senha_atual;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
