/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import Classes.Despesa;
import DAO.DespesaDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author m10816361
 */
public class Tela_Despesa extends javax.swing.JInternalFrame {

    ArrayList<Despesa> despesas = new ArrayList();
    DespesaDao despesaDao = new DespesaDao();
    Despesa despesa = new Despesa();

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    /**
     * Creates new form Tela_Produto
     */
    public Tela_Despesa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nome = new javax.swing.JLabel();
        lbl_nascimento = new javax.swing.JLabel();
        lbl_endereco = new javax.swing.JLabel();
        lbl_telefone = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_tipo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_descricao = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_editar_Despesa = new javax.swing.JTable();
        btn_buscar_pelo_tipo = new javax.swing.JButton();
        txt_busca_por_tipo = new javax.swing.JTextField();
        lbl_buscar_pelo_nome = new javax.swing.JLabel();
        btn_limpar = new javax.swing.JButton();
        btn_inserir = new javax.swing.JButton();
        btn_apagar = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_preco = new javax.swing.JTextField();
        txt_Data = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        lbl_nome.setText("Tipo:");

        lbl_nascimento.setText("Descrição:");

        lbl_endereco.setText("Data:");

        lbl_telefone.setText("Valor:");

        lbl_id.setText("Id:");

        txt_id.setVisible(true);
        txt_id.setEditable(false);

        txt_descricao.setColumns(20);
        txt_descricao.setRows(5);
        jScrollPane1.setViewportView(txt_descricao);

        table_editar_Despesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tipo", "Descrição", "Valor", "Data"
            }
        ));
        table_editar_Despesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_editar_DespesaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_editar_Despesa);

        btn_buscar_pelo_tipo.setText("Buscar");
        btn_buscar_pelo_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_pelo_tipoActionPerformed(evt);
            }
        });

        lbl_buscar_pelo_nome.setText("Buscar  pelo tipo :");

        btn_limpar.setText("Limpar");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        btn_inserir.setText("Inserir");
        btn_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inserirActionPerformed(evt);
            }
        });

        btn_apagar.setText("Apagar");
        btn_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apagarActionPerformed(evt);
            }
        });

        btn_Editar.setText("Atualizar");
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tela de Edição das Despesas");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("00.00");

        txt_id.setVisible(true);
        txt_id.setEditable(false);

        txt_Data.setVisible(true);
        txt_Data.setEditable(true);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("dd/MM/aaaa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_id)
                    .addComponent(lbl_telefone)
                    .addComponent(lbl_endereco)
                    .addComponent(lbl_nascimento)
                    .addComponent(lbl_nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tipo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btn_inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txt_preco, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(txt_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_buscar_pelo_nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_busca_por_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_buscar_pelo_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_buscar_pelo_nome)
                    .addComponent(txt_busca_por_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btn_buscar_pelo_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_id))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_endereco)
                            .addComponent(txt_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_telefone)
                            .addComponent(jLabel5)
                            .addComponent(txt_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nascimento)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_inserir)
                    .addComponent(btn_Editar)
                    .addComponent(btn_apagar)
                    .addComponent(btn_limpar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_editar_DespesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_editar_DespesaMouseClicked

        try {
            Integer indice = table_editar_Despesa.getSelectedRow();
            String tipo = "" + table_editar_Despesa.getValueAt(table_editar_Despesa.getSelectedRow(), 1);
            Despesa despesa = new Despesa();
            despesa = despesas.get(indice);

            txt_id.setText(despesa.getId().toString());
            txt_tipo.setText(despesa.getTipo().toString());
            txt_Data.setText(despesa.getData_despesa().toString());
            txt_preco.setText(despesa.getTotal().toString());
            txt_descricao.setText(despesa.getDescricao().toString());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Por favor, clique em uma linha válida.");
        }
    }//GEN-LAST:event_table_editar_DespesaMouseClicked

    private void btn_buscar_pelo_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_pelo_tipoActionPerformed

        String tipo_despesa = txt_busca_por_tipo.getText();
        DespesaDao despesaDao = new DespesaDao();
        Despesa despesa = new Despesa();

        DefaultTableModel model = (DefaultTableModel) table_editar_Despesa.getModel();
        model.setRowCount(0);

        if (txt_busca_por_tipo.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, digite um tipo de despesa para realizar a busca.");
            limpar();
        } else {

            try {
                despesas = despesaDao.buscarDespesa(tipo_despesa);

                if (despesas.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Despesa não encontrada.");
                    txt_busca_por_tipo.setText("");
                    limpar();
                }
            } catch (ClassNotFoundException ex) {
                JOptionPane.showInternalMessageDialog(null, "Erro, favor contatar o Administrador do sistema:");
            }

            atualizar_tbl_despesa();
        }

    }//GEN-LAST:event_btn_buscar_pelo_tipoActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        limpar();
        atualizar_tbl_despesa();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inserirActionPerformed

        boolean inserir;
        boolean validar;
        Integer resposta;

        validar = validar_inserir_atualizar();
        if (validar == true) {
            resposta = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Inserir o Item Selecionado?");
            if (resposta == JOptionPane.YES_OPTION) {
                try {
                    inserir = despesaDao.inserir(despesa);
                    if (inserir == true) {
                        JOptionPane.showMessageDialog(null, "Despesa Inserida com sucesso.");
                        txt_busca_por_tipo.setText(despesa.getTipo());
                        atualizar_tbl_despesa();
                        limpar();
                    } else {
                      JOptionPane.showMessageDialog(null, "Erro, Dados não Inseridos, confira os dados e tente novamente.");
                    }
                } catch (SQLException ex) {
                    JOptionPane.showInternalMessageDialog(null, "Erro, Verifique a conexão com o banco de Dados:");
                } catch (ClassNotFoundException ex) {
                    JOptionPane.showInternalMessageDialog(null, "Erro, favor contatar o Administrador do sistema:");
                } catch (NumberFormatException ex) {
                    JOptionPane.showInternalMessageDialog(null, "Erro, Digite os números corretamente:");
                }
            }
    }//GEN-LAST:event_btn_inserirActionPerformed
    }

    private void btn_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apagarActionPerformed

        Integer indice = table_editar_Despesa.getSelectedRow();
        Despesa despesa = new Despesa();
        if (indice > -1) {
            despesa = despesas.get(indice);
            DespesaDao despesaDao = new DespesaDao();
            boolean apagar;
            Integer resposta;
            resposta = JOptionPane.showConfirmDialog(null, "Certeza que deseja Apagar o Item Selecionado?");
            if (resposta == JOptionPane.YES_OPTION) {
                try {
                    apagar = despesaDao.Apagar(despesa.getId());
                    JOptionPane.showInternalMessageDialog(null, "Dados apagados com sucesso?");
                    txt_busca_por_tipo.setText(despesa.getTipo());
                    limpar();
                    atualizar_tbl_despesa();
                    // TODO add your handling code here:
                } catch (ClassNotFoundException ex) {
                    JOptionPane.showInternalMessageDialog(null, "Erro, favor contatar o Administrador do sistema:");
                }
            }
        } else {
            JOptionPane.showInternalMessageDialog(null, "Favor clique no item da tabela que deseja excluir:");
        }
    }//GEN-LAST:event_btn_apagarActionPerformed

    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed

        boolean inserir;
        boolean validar;
        Integer resposta;

        validar = validar_inserir_atualizar();
        if (validar == true) {
            resposta = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Atualizar o Item Selecionado?");
            if (resposta == JOptionPane.YES_OPTION) {
                try {
                    despesa.setId(Integer.valueOf(txt_id.getText()));
                    inserir = despesaDao.Atualizar(despesa);
                    if (inserir == true) {
                        JOptionPane.showMessageDialog(null, "Despesa Atualizada com sucesso.");
                        txt_busca_por_tipo.setText(despesa.getTipo());
                        atualizar_tbl_despesa();
                        limpar();
                    } else {
                        JOptionPane.showMessageDialog(null, "Erro, Dados não Atualizados, confira os dados e tente novamente.");
                                        }
                } catch (SQLException ex) {
                    JOptionPane.showInternalMessageDialog(null, "Erro, Verifique a conexão com o banco de Dados:");
                } catch (ClassNotFoundException ex) {
                    JOptionPane.showInternalMessageDialog(null, "Erro, favor contatar o Administrador do sistema:");
                } catch (NumberFormatException ex) {
                    JOptionPane.showInternalMessageDialog(null, "Erro, Digite os números corretamente:");
                }
            }
        }
    }//GEN-LAST:event_btn_EditarActionPerformed

    private void atualizar_tbl_despesa() {

        String busca_despesa = txt_busca_por_tipo.getText();
        DespesaDao despesaDao = new DespesaDao();
        Despesa despesa = new Despesa();
        DefaultTableModel model = (DefaultTableModel) table_editar_Despesa.getModel();
        model.setRowCount(0);

        if (txt_busca_por_tipo.getText().trim().equals("")) {
        } else {
            try {
                despesas = despesaDao.buscarDespesa(busca_despesa);

            } catch (ClassNotFoundException ex) {
                JOptionPane.showInternalMessageDialog(null, "Erro, favor contatar o Administrador do sistema:");
            }
            for (Despesa d : despesas) {
                String tipo;
                String descricao;
                String valor;
                String data_despesa;
                d.setData_despesa(datas_vindas_mysql(d));
                tipo = d.getTipo();
                descricao = d.getDescricao();
                data_despesa = d.getData_despesa();
                valor = NumberFormat.getCurrencyInstance().format(d.getTotal());
                model.addRow(new Object[]{tipo, descricao, valor, data_despesa});
            }
        }
    }

    boolean validar_inserir_atualizar() {

        String datas = datas_para_mysql();

        if (datas != "") {
            if (txt_tipo.getText().trim().equals("") || txt_preco.getText().trim().equals("")) {
                JOptionPane.showInternalMessageDialog(null, "Erro, Insira todos os dados:");
                return false;
            } else {
                try {
                    String data_atual = datas_para_mysql();
                    despesa.setTipo(txt_tipo.getText());
                    despesa.setDescricao(txt_descricao.getText());
                    despesa.setData_despesa(data_atual);
                    despesa.setTotal(Float.valueOf(txt_preco.getText()));
                    return true;
                } catch (NumberFormatException ex) {
                    JOptionPane.showInternalMessageDialog(null, "Erro, Dados inválidos:");
                    return false;
                }
            }
        }
        return false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_apagar;
    private javax.swing.JButton btn_buscar_pelo_tipo;
    private javax.swing.JButton btn_inserir;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_buscar_pelo_nome;
    private javax.swing.JLabel lbl_endereco;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_nascimento;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_telefone;
    private javax.swing.JTable table_editar_Despesa;
    private javax.swing.JTextField txt_Data;
    private javax.swing.JTextField txt_busca_por_tipo;
    private javax.swing.JTextArea txt_descricao;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_preco;
    private javax.swing.JTextField txt_tipo;
    // End of variables declaration//GEN-END:variables

    private void limpar() {

        txt_Data.setText("");
        txt_busca_por_tipo.setText("");
        txt_id.setText("");
        txt_tipo.setText("");
        txt_preco.setText("");
        txt_preco.setText("");
        txt_descricao.setText("");
    }

    private String datas_para_mysql() {
        try {
            String dia = txt_Data.getText().substring(0, 2);
            String mes = txt_Data.getText().substring(3, 5);
            String ano = txt_Data.getText().substring(6);
            String data_para_mysql = ano + "-" + mes + "-" + dia;
            return data_para_mysql;
        } catch (StringIndexOutOfBoundsException e) {
            JOptionPane.showInternalMessageDialog(null, "Erro, Favor preencha todos os dados:");
            return "";
        }
    }

    private String datas_vindas_mysql(Despesa despesa) {

        try {
            String data = despesa.getData_despesa();
            String dia = data.substring(8);
            String mes = data.substring(5, 7);
            String ano = data.substring(0, 4);
            String data_mysql = dia + "/" + mes + "/" + ano;
            return data_mysql;
        } catch (StringIndexOutOfBoundsException e) {
            JOptionPane.showInternalMessageDialog(null, "Erro, Favor preencha todos os dados:");
            return "";
        }

    }
}
